### PR TITLE
e3phoenix: Adding enhance elixir extism example

### PR DESCRIPTION
**Pull request by Benanna2019**
Example using enhance-ssr/wasm with extism in an Elixir/Phoenix LiveView application.

### CODE REVIEW

**Comment by Benanna2019** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Benanna2019 — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by Benanna2019** [comment]
recheck

**Comment by Benanna2019** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Benanna2019** [comment]
recheck

**Comment by Benanna2019** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by macdonst** [comment]
recheck

**Pull request closed without merging**
